---
abstract: 'A Mouse role for logging'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  IO::Scalar: 0
  Test::More: 0
  ok: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MouseX-Log-Dispatch-Config
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  Log::Dispatch::Config: 0
  Mouse: 0.15
  MouseX::Types: 0.01
  namespace::clean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
